# str='abcde f'
# print('str',str)
# print('str[2:4]',str[2:4])
# print('str[1:4]',str[1:4])
# print("str[1]",str[1])
# print("str[4]",str[4])
# print("str[2]",str[2])
# print(str[:6]+'a')
L=['Google', 'Runoob', 'Taobao']
L.pop()
print(L)
L.insert(2,"s")
print(L)
L.reverse()
print(L)